# This configuration is for development only!
# If you're looking for an example configuration, take a look at the sample_config.yml.

webserver:
  host: localhost:8080
  write_timeout: 5
  read_timeout: 5
  tls: false
  cert: path to ssl certificate
  private_key: path to ssl private key
auth:
  mode: standard  # Possible values: none, standard, oauth
  admin_password: admin
  moderator_password: mod
  read_only_password: ro
  timeout: 5h
  oauth:  # OAuth2 configuration (used only when mode is oauth)
    provider: ""     # e.g., github, google
    client_id: ""
    client_secret: ""
    callback_url: ""
acc:
  server_path: "/app/fake-accserver/build/osx"
  server_exe: accServer.exe

config_path: config/
dev: true
skip_wine: true
loglevel: debug
cors:
  origins: "*"
  loglevel: info
